const exec = require('child_process');

const keychain = {}
/**
 *	@example add( 'alice', 'svn://plugins.svn.wordpress.org/', 'myverysecret', 'Generated by some piece of code' )
 */
keychain['darwin'] = {
	add: ( user, url, pw, comment='' ) => {
		const comment_part = '' !== comment ? `-j "${comment}"` : ''
		const parsedURL = new URL(url)
		let ret
		parsedURL.username = user
		try {
			ret = exec.execSync( `security add-generic-password -a "${user}" -l "${parsedURL.href}" -s "${url}" ${comment_part} -w "${pw}"`, { encoding: 'utf8' } );
		} catch (err) {
			ret = false
		}
		return ret
	},
	get: ( user, url ) => {
		let ret
		try {
			ret = exec.execSync( `security find-generic-password -a ${user} -s "${url}" -w`, { encoding: 'utf8' } ).trim()
		} catch(err) {
			ret = false
		}
		return ret
	},
	remove: (user,url) => {
		let ret
		try {
			ret = exec.execSync( `security delete-generic-password -a ${user} -s "${url}"`, { encoding: 'utf8' } )
		} catch(err) {
			ret = false
		}
		return ret
	}
}

keychain.default = {
	add: ( user, url, pw, comment='' ) => {
		console.log( `not implemented on ${process.platform}` )
	},
	get: ( user, url ) => {
		console.log( `not implemented on ${process.platform}` )
	},
	remove: ( user, url ) => {
		console.log( `not implemented on ${process.platform}` )
	}
}

module.exports = keychain[process.platform]
